// <auto-generated />
namespace MT.DataAccess.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class user_remove_dtStamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_remove_dtStamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201409191052348_user_remove_dtStamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
